package jdbcFirst;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.postgresql.Driver;

import jdbcFirst.util.ConnectionManager;

public class JdbcRunner {
	public static void main(String[] args) throws SQLException{
		Class<Driver> driverClass = Driver.class;
		String sql1 = """
				CREATE TABLE IF NOT EXISTS info (
					id SERIAL PRIMARY KEY ,
					data TEXT NOT NULL
				);
				 """;
		String sql2 = """
				DROP DATABASE inn;
				 """;
		String sql3 = """
				DROP TABLE info;
				 """;
		String sql4 = """
				SELECT * FROM ticket
				WHERE id=5;
				 """;
		String sql5 = """
				INSERT INTO info (data)
				VALUES 
				('autogenerated')
				 """;
		try (Connection connection = ConnectionManager.open();
				Statement statement = connection.createStatement()
			) {
			System.out.println(connection.getTransactionIsolation());
			statement.execute(sql1);
//			boolean executeResult = statement.execute(sql3);
//			System.out.println(executeResult);
			System.out.println("-------------");
			ResultSet executeResultQuery = statement.executeQuery(sql4);
			while(executeResultQuery.next()) {
				System.out.println(executeResultQuery.getLong("id"));
				System.out.println(executeResultQuery.getString("passenger_no"));
				System.out.println(executeResultQuery.getBigDecimal("cost"));
				System.out.println("----------");
			}
			int executeResultUpdate = statement.executeUpdate(sql5, Statement.RETURN_GENERATED_KEYS);
			ResultSet generatedKeys = statement.getGeneratedKeys();
			if (generatedKeys.next()) {
				int generatedId = generatedKeys.getInt("id");
				System.out.println(generatedId);
			}
		}		
	}
}